#!/usr/bin/env bash

query_entries() {
    # safe queried url for choose_entry
    export queried_url="$1"
    mapfile -t files < <(find -L "$PREFIX" -iname '*.gpg' -printf '%P\n' |sed 's,\.gpg$,,')
}

choose_entry() {
    MENU_COMMAND=(
        rofi -dmenu
            -p "qutebrowser> "
            -filter "$queried_url"
            -mesg $'Pick a password entry for <b>'"${QUTE_URL//&/&amp;}"'</b>'
    )
    file=$( printf "%s\n" "${files[@]}" | "${MENU_COMMAND[@]}" )
}


