;;; init.el --- personal Emacs config (post-Doom) -*- lexical-binding: t; -*-

;;; Package bootstrap ---------------------------------------------------------

(require 'cl-lib)
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
;; `package-quickstart' (set in early-init.el) precompiles every package's
;; autoloads and load-path into `package-quickstart.el'.  `package-activate-all'
;; loads that single file instead of scanning each package dir the way
;; `package-initialize' does -- ~0.22s faster.  The file is regenerated by
;; `my/install-packages'; if it is missing, fall back to the slow scan.
(if (file-exists-p (expand-file-name "package-quickstart.el" user-emacs-directory))
    (package-activate-all)
  (package-initialize))

(defun a-list (&rest pairs)
  "Build an alist from alternating KEYWORD FUNCTION arguments.
Each :NAME keyword becomes the symbol NAME in the car of the cell."
  (let (result)
    (while pairs
      (let ((key (pop pairs))
            (fn  (pop pairs)))
        (push (cons (intern (substring (symbol-name key) 1)) fn) result)))
    (nreverse result)))

(defvar my/packages
  (a-list
   :evil
   (lambda ()
     (setq evil-want-keybinding nil)    ; play nicely with other modes
     (require 'evil)
     (evil-mode 1)

     ;; Move by visual lines.
     (dolist (map (list evil-normal-state-map
                        evil-visual-state-map
                        evil-motion-state-map))
       (define-key map (kbd "j") #'evil-next-visual-line)
       (define-key map (kbd "k") #'evil-previous-visual-line))

     ;; Cursor: shape + colour per state (colour must go through evil,
     ;; not the `cursor' face).
     (setq evil-normal-state-cursor   '(box       "#ff9900")
           evil-insert-state-cursor   '((bar . 2) "#ff9900")
           evil-visual-state-cursor   '(hollow    "#ff9900")
           evil-replace-state-cursor  '(hbar      "#ff9900")
           evil-operator-state-cursor '(hbar      "#ff9900")
           evil-motion-state-cursor   '(box       "#ff9900")
           evil-emacs-state-cursor    '(bar       "#ff9900")))

   :gruvbox-theme
   (lambda ()
     (load-theme 'gruvbox t)
     ;; Overrides layered on top of the theme.
     ;; On a graphical frame use the solid background; on a TTY keep the
     ;; background unspecified so the terminal's transparency shows through
     ;; (otherwise loading the theme re-opacifies the frame until
     ;; `my/unspecify-tty-background' runs at `window-setup-hook').
     (custom-set-faces
      '(line-number ((t (:inherit default :background "black" :foreground "#928374"))))
      '(line-number-current-line ((t (:inherit line-number :background "#3c3836"))))
      '(hl-line     ((t (:background "#3c3836"))))
      '(default     ((((type graphic)) (:background "#181818" :foreground "#EBDBB2"))
                     (t                (:background "unspecified-bg" :foreground "#EBDBB2"))))))

   :which-key
   (lambda ()
     (which-key-mode 1))

   :magit
   (lambda ()
     (global-set-key (kbd "C-x g") #'magit-status)))
  "Alist of (PACKAGE . CONFIG-FUNCTION).
`my/install-packages' installs each missing PACKAGE, and
`my/configure-packages' calls each CONFIG-FUNCTION whose package is
installed.  All package-specific configuration lives inside the
respective function.")

(defun my/install-packages ()
  "Install or update every package in `my/packages'.
Progress is shown in a dedicated buffer.  Run this manually via
\\[my/install-packages]; it is not called on startup."
  (interactive)
  (let* ((buffer (get-buffer-create "*my-package-install*"))
         (out (lambda (fmt &rest args)
                (with-current-buffer buffer
                  (goto-char (point-max))
                  (let ((inhibit-read-only t))
                    (insert (apply #'format fmt args) "\n")))
                (redisplay t)))
         ;; Mirror package.el's own `message' output into the buffer.
         (relay (lambda (orig fmt &rest args)
                  (when fmt (ignore-errors (apply out fmt args)))
                  (apply orig fmt args))))
    (with-current-buffer buffer
      (setq buffer-read-only nil)
      (erase-buffer))
    ;; Show the buffer *before* doing the work so progress is visible live.
    (pop-to-buffer buffer)
    (advice-add 'message :around relay)
    (unwind-protect
        (progn
          (funcall out "Refreshing package archives...")
          (package-refresh-contents)
          (dolist (cell my/packages)
            (let ((pkg (car cell)))
              (funcall out "== %s ==" pkg)
              (condition-case err
                  (if (package-installed-p pkg)
                      (package-upgrade pkg)
                    (package-install pkg))
                (error (funcall out "  %s: %s" pkg (error-message-string err))))))
          ;; Rebuild the quickstart file so the next startup uses the fast path.
          (funcall out "Refreshing package-quickstart...")
          (package-quickstart-refresh))
      (advice-remove 'message relay))
    (funcall out "Finished.")))

(defun my/configure-packages ()
  "Run each config function from `my/packages' whose package is installed."
  (dolist (cell my/packages)
    (when (package-installed-p (car cell))
      (funcall (cdr cell)))))

(my/configure-packages)

;;; Identity ------------------------------------------------------------------

(setq user-full-name "Thorsten Wißmann"
      user-mail-address "edu@thorsten-wissmann.de")

;;; Sane defaults -------------------------------------------------------------

(setq confirm-kill-processes nil        ; kill processes on exit without asking
      confirm-kill-emacs nil            ; exit without confirmation
      inhibit-startup-screen t
      ring-bell-function 'ignore)
(setq-default indent-tabs-mode nil)
(menu-bar-mode -1)
(when (fboundp 'tool-bar-mode) (tool-bar-mode -1))
(when (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))

;; Keep customize-set options out of this file.
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(when (file-exists-p custom-file) (load custom-file nil t))

;;; Line numbers --------------------------------------------------------------

(setq display-line-numbers-type t)
(setq-default display-line-numbers-width 0        ; hug the actual digits
              display-line-numbers-grow-only t)   ; shrink back when possible
(global-display-line-numbers-mode 1)

(defun my/line-number-width-from-buffer ()
  "Reserve line-number columns to fit this buffer's total line count."
  (setq-local display-line-numbers-width
              (length (number-to-string (line-number-at-pos (point-max))))))
(add-hook 'display-line-numbers-mode-hook #'my/line-number-width-from-buffer)
(add-hook 'after-save-hook #'my/line-number-width-from-buffer)

;;; Cursorline (vim-like current-line highlight) ------------------------------

(global-hl-line-mode 1)

;;; Frame appearance ----------------------------------------------------------

(add-to-list 'default-frame-alist '(alpha-background . 93))

;; On a TTY, let the terminal's own background show through.
(defun my/unspecify-tty-background (&optional frame)
  (unless (display-graphic-p frame)
    (set-face-background 'default "unspecified-bg" frame)))
(add-hook 'window-setup-hook #'my/unspecify-tty-background)
(add-hook 'after-make-frame-functions #'my/unspecify-tty-background)

;;; Font: size chosen from display DPI, set per-frame -------------------------

(defun my/display-dpi (&optional frame)
  "Return the DPI of FRAME's display, or nil if unknown."
  (let* ((attrs (car (display-monitor-attributes-list frame)))
         (mm    (alist-get 'mm-size attrs))
         (geom  (alist-get 'geometry attrs)))
    (when (and mm geom (> (car mm) 0))
      (/ (float (nth 2 geom))            ; width in pixels
         (/ (car mm) 25.4)))))           ; width in inches

(defun my/font-size-for-dpi (&optional frame)
  "Pick a font point size based on FRAME's display DPI."
  (let ((dpi (or (my/display-dpi frame) 96)))
    (cond ((>= dpi 190) 18)              ; hidpi / retina
          ((>= dpi 140) 14)              ; medium-high
          (t            12))))           ; standard

(defun my/set-font-for-frame (&optional frame)
  "Set the frame font once a graphical FRAME exists (needed under daemon)."
  (when (display-graphic-p frame)
    (set-frame-font (font-spec :name "Bitstream Vera Sans Mono"
                               :size (my/font-size-for-dpi frame))
                    nil (list frame))))
(add-hook 'after-make-frame-functions #'my/set-font-for-frame)
(add-hook 'window-setup-hook #'my/set-font-for-frame)

;;; Agda input method everywhere ---------------------------------------------

;; Load agda-input.el shipped with the Agda binary (version-agnostic glob).
(let ((agda-input (car (last (file-expand-wildcards
                              "~/.local/share/agda/*/emacs-mode/agda-input.el")))))
  (when agda-input
    (add-to-list 'load-path (file-name-directory agda-input))
    (require 'agda-input)
    (add-hook 'evil-insert-state-entry-hook (lambda () (set-input-method "Agda")))
    (add-hook 'evil-insert-state-exit-hook  (lambda () (set-input-method nil)))))

;;; init.el ends here
