;;; vimacs.el --- package install/configure helpers -*- lexical-binding: t; -*-

;;; Commentary:
;; Helper functions used by init.el to declare, install, and configure
;; packages: `configure-packages' records the (PACKAGE . CONFIG-FUNCTION)
;; alist and runs each config function, and `my/install-packages'
;; installs/updates them.

;;; Code:

(require 'package)

(defun my/activate-packages ()
  "Activate installed packages, preferring the fast quickstart path.
`package-quickstart' (set in early-init.el) precompiles every package's
autoloads and load-path into `package-quickstart.el'.  Loading that single
file via `package-activate-all' is ~0.22s faster than `package-initialize',
which scans each package dir.  The file is regenerated by
`my/install-packages'; fall back to the slow scan when it is missing."
  (if (file-exists-p (expand-file-name "package-quickstart.el" user-emacs-directory))
      (package-activate-all)
    (package-initialize)))

;; Activate packages as soon as this file is loaded, so the configuration
;; below (and in init.el) sees them.
(my/activate-packages)

(defun my/load-custom-file ()
  "Point `custom-file' at custom.el and load it if it exists.
Keeps `customize'-written settings out of the hand-maintained init files."
  (setq custom-file (expand-file-name "custom.el" user-emacs-directory))
  (when (file-exists-p custom-file) (load custom-file nil t)))

;; Load customize output as soon as this file is loaded.
(my/load-custom-file)

(defvar my/packages nil
  "Alist of (PACKAGE . CONFIG-FUNCTION), set by `configure-packages'.
`my/install-packages' installs each missing PACKAGE.")

(defun configure-packages (&rest pairs)
  "Declare packages from alternating :NAME CONFIG-FUNCTION arguments.
Each :NAME keyword becomes the symbol NAME.  The resulting
\(PACKAGE . CONFIG-FUNCTION) alist is stored in `my/packages' for
`my/install-packages', and each CONFIG-FUNCTION whose package is
installed is called."
  (setq my/packages
        (let (result)
          (while pairs
            (let ((key (pop pairs))
                  (fn  (pop pairs)))
              (push (cons (intern (substring (symbol-name key) 1)) fn) result)))
          (nreverse result)))
  (dolist (cell my/packages)
    (when (package-installed-p (car cell))
      (funcall (cdr cell)))))

(defun my/--run-package-op (buffer-name action)
  "Run ACTION over `my/packages', reporting progress.
ACTION is called with two arguments: a package symbol and an OUT
function \(FMT &rest ARGS) for logging.  Interactively, progress is
shown in a buffer named BUFFER-NAME; in batch mode it is printed to the
terminal instead.  Archives are refreshed first and the quickstart file
is rebuilt afterwards."
  (let* ((buffer (unless noninteractive (get-buffer-create buffer-name)))
         (out (lambda (fmt &rest args)
                (if noninteractive
                    ;; `message' goes to stderr in batch mode.
                    (message "%s" (apply #'format fmt args))
                  (with-current-buffer buffer
                    (goto-char (point-max))
                    (let ((inhibit-read-only t))
                      (insert (apply #'format fmt args) "\n")))
                  (redisplay t))))
         ;; Mirror package.el's own `message' output into the buffer.  In batch
         ;; mode package.el already logs to stderr, so leave `message' alone
         ;; (advising it here would recurse through `out').
         (relay (lambda (orig fmt &rest args)
                  (when fmt (ignore-errors (apply out fmt args)))
                  (apply orig fmt args))))
    (unless noninteractive
      (with-current-buffer buffer
        (setq buffer-read-only nil)
        (erase-buffer))
      ;; Show the buffer *before* doing the work so progress is visible live.
      (pop-to-buffer buffer)
      (advice-add 'message :around relay))
    (unwind-protect
        (progn
          (funcall out "Refreshing package archives...")
          (package-refresh-contents)
          (dolist (cell my/packages)
            (let ((pkg (car cell)))
              (condition-case err
                  (funcall action pkg out)
                (error (funcall out "  %s: %s" pkg (error-message-string err))))))
          ;; Rebuild the quickstart file so the next startup uses the fast path.
          (funcall out "Refreshing package-quickstart...")
          (package-quickstart-refresh))
      (unless noninteractive (advice-remove 'message relay)))
    (funcall out "Finished.")))

(defun my/install-packages ()
  "Install every missing package in `my/packages'.
Already-installed packages are left untouched; use `my/update-packages'
to upgrade them.  Interactively, progress is shown in a dedicated
buffer.  In batch mode it is printed to the terminal instead, so this
can be driven from a shell:

    emacs --batch -l ~/.emacs.d/init.el -f my/install-packages

Run interactively via \\[my/install-packages]; it is not called on startup."
  (interactive)
  (my/--run-package-op
   "*my-package-install*"
   (lambda (pkg out)
     (unless (package-installed-p pkg)
       (funcall out "== installing %s ==" pkg)
       (package-install pkg)))))

(defun my/update-packages ()
  "Upgrade every installed package in `my/packages'.
Missing packages are installed as well, so this brings everything up to
date.  Interactively, progress is shown in a dedicated buffer.  In batch
mode it is printed to the terminal instead, so this can be driven from a
shell:

    emacs --batch -l ~/.emacs.d/init.el -f my/update-packages

Run interactively via \\[my/update-packages]; it is not called on startup."
  (interactive)
  (my/--run-package-op
   "*my-package-update*"
   (lambda (pkg out)
     (if (package-installed-p pkg)
         (progn (funcall out "== upgrading %s ==" pkg)
                (package-upgrade pkg))
       (funcall out "== installing %s ==" pkg)
       (package-install pkg)))))

;;; Font: size chosen from display DPI, set per-frame -------------------------

(defun my/display-dpi (&optional frame)
  "Return the DPI of FRAME's display, or nil if unknown."
  (let* ((attrs (car (display-monitor-attributes-list frame)))
         (mm    (alist-get 'mm-size attrs))
         (geom  (alist-get 'geometry attrs)))
    (when (and mm geom (> (car mm) 0))
      (/ (float (nth 2 geom))            ; width in pixels
         (/ (car mm) 25.4)))))           ; width in inches

(defvar my/font-size-function (lambda (_dpi) 12)
  "Function mapping a display DPI to a font point size.
Set it with `set-conditional-font-size'.")

(defun set-conditional-font-size (fn)
  "Use FN to choose the font point size from a display DPI.
FN is called with one argument, the DPI, and returns a point size."
  (setq my/font-size-function fn))

(defun my/font-size-for-dpi (&optional frame)
  "Pick a font point size based on FRAME's display DPI."
  (funcall my/font-size-function (or (my/display-dpi frame) 96)))

(defun my/set-font-for-frame (&optional frame)
  "Set the frame font once a graphical FRAME exists (needed under daemon)."
  (when (display-graphic-p frame)
    (set-frame-font (font-spec :name "Bitstream Vera Sans Mono"
                               :size (my/font-size-for-dpi frame))
                    nil (list frame))))
(add-hook 'after-make-frame-functions #'my/set-font-for-frame)
(add-hook 'window-setup-hook #'my/set-font-for-frame)

;;; Mode line / window title: project-relative buffer path --------------------

;; Doom-style buffer identification: the path relative to the project root,
;; with the directory dimmed and the file name bright, in place of the stock
;; bare `%12b' buffer name -- and the same path in the window title.
;; Configured from init.el via `set-buffer-path-mode-line'; the faces below
;; are left empty here so that call is the single place colours are chosen.

(declare-function project-root "project" (project))
(defvar xterm-set-window-title)         ; term/xterm.el, loaded at terminal init

(defface my/mode-line-dir '((t nil))
  "Face for the directory part of the path in the mode line.")

(defface my/mode-line-file '((t nil))
  "Face for the file-name part of the path in the mode line.")

(defface my/mode-line-path-inactive '((t (:inherit mode-line-inactive)))
  "Face for the whole path in the mode line of an unselected window.")

(defun my/mode-line--shorten-path (file)
  "Shorten FILE to PROJECT/path/to/file, or `~'-abbreviate it if projectless.
The leading component is the project directory's own name, so the result
identifies the project without repeating where it is checked out."
  (let ((root (when-let* ((project (project-current nil (file-name-directory file))))
                (expand-file-name (project-root project)))))
    (if (and root (string-prefix-p root (expand-file-name file)))
        (concat (file-name-nondirectory (directory-file-name root)) "/"
                (file-relative-name file root))
      (abbreviate-file-name file))))

(defvar-local my/mode-line--path-cache nil
  "Cons of (FILE . SHORTENED) memoising `my/mode-line--shorten-path'.
`project-current' walks up the directory tree looking for a VC root, which
is far too slow to repeat on every redisplay of the mode line -- and the
window title is refreshed from `post-command-hook' on top of that.  Keyed
on the file name, so a rename or `write-file' recomputes it.")

(defun my/buffer-path ()
  "Shortened path of this buffer, or its name if it visits no file.
Shared by the mode line and the frame/terminal title."
  (let ((file (buffer-file-name)))
    (cond ((null file) (buffer-name))
          ((equal (car my/mode-line--path-cache) file)
           (cdr my/mode-line--path-cache))
          (t (cdr (setq my/mode-line--path-cache
                        (cons file (my/mode-line--shorten-path file))))))))

(defun my/mode-line-buffer-path ()
  "Buffer path for the mode line: dimmed dirname + highlighted file name.
Buffers not visiting a file show their buffer name.  In an unselected
window the whole thing is dimmed, as the stock mode line does."
  (let* ((file (buffer-file-name))
         (path (my/buffer-path))
         (str
          (cond
           ((not (mode-line-window-selected-p))
            (propertize path 'face 'my/mode-line-path-inactive))
           ((null file)
            (propertize path 'face 'my/mode-line-file))
           (t
            (concat (propertize (or (file-name-directory path) "")
                                'face 'my/mode-line-dir)
                    (propertize (file-name-nondirectory path)
                                'face 'my/mode-line-file))))))
    ;; Keep the stock mouse behaviour (mouse-1/3 cycle buffers) and tooltip.
    (propertize str
                'help-echo (or file (buffer-name))
                'mouse-face 'mode-line-highlight
                'local-map mode-line-buffer-identification-keymap)))

(defun my/colour-depth-spec (attribute colour)
  "Face spec setting ATTRIBUTE to COLOUR, per the display's colour depth.
COLOUR is either one colour used everywhere, or a list

    \(TRUECOLOR COLOR256 FALLBACK)

picking one per depth.  The split matters because Emacs approximates a hex
colour into the xterm 256-colour cube itself, and lands well off: the
gruvbox mode-line background #37302f becomes the olive `color-58', which
is why the mode line looks green inside tmux (TERM=screen-256color) but
right in a truecolor terminal.  Naming the 256-colour palette entry
explicitly -- \"color-236\" and friends -- side-steps that guess.
FALLBACK covers terminals below 256 colours, where only the 8 ANSI names
\(\"black\" is SGR 40, and so on) are safe."
  (if (not (consp colour))
      `((t (,attribute ,colour)))
    (let ((truecolor (nth 0 colour))
          (c256      (nth 1 colour))
          (fallback  (nth 2 colour)))
      ;; The graphic branch comes first: `color-236' & co. are tty palette
      ;; names, meaningless to a window system, so a graphical frame must
      ;; never reach the 256-colour branch even on an 8-bit visual.
      `((((type graphic))        (,attribute ,truecolor))
        (((min-colors 16777216)) (,attribute ,truecolor))
        (((min-colors 256))      (,attribute ,c256))
        (t                       (,attribute ,fallback))))))

(defun set-buffer-path-mode-line (&rest colours)
  "Put the project-relative buffer path in the mode line and the window title.
COLOURS is a plist; each value is a colour in the form accepted by
`my/colour-depth-spec' \(one colour, or a per-depth triple):

  :dir                 foreground of the directory part of the path
  :file                foreground of the file name
  :background          `mode-line' background
  :inactive-background `mode-line-inactive' background

The two background keys are optional; omit them to keep whatever the theme
chose.  They are set as face *overrides*, so they also survive a later
`load-theme'."
  (let ((dir     (plist-get colours :dir))
        (file    (plist-get colours :file))
        (bg      (plist-get colours :background))
        (inactive-bg (plist-get colours :inactive-background)))
    (when dir  (face-spec-set 'my/mode-line-dir  (my/colour-depth-spec :foreground dir)))
    (when file (face-spec-set 'my/mode-line-file
                              (let ((spec (my/colour-depth-spec :foreground file)))
                                ;; Bold on top of whichever depth branch applies.
                                (mapcar (lambda (entry)
                                          (list (car entry)
                                                (append (cadr entry) '(:weight bold))))
                                        spec))))
    (when bg (face-spec-set 'mode-line (my/colour-depth-spec :background bg)))
    (when inactive-bg
      (face-spec-set 'mode-line-inactive (my/colour-depth-spec :background inactive-bg))))

  ;; Buffer-local in every buffer, so this sets the value for the buffers that
  ;; do not override it themselves (dired, Info, … keep their own).
  (setq-default mode-line-buffer-identification
                '(:eval (my/mode-line-buffer-path)))

  ;; Same path in the title, minus the faces (a title is plain text), with a
  ;; suffix naming the application -- a bare path in a window list or taskbar
  ;; gives no hint of what is showing it.  Covers graphical frames as well as
  ;; terminal ones.
  (setq frame-title-format '((:eval (my/buffer-path)) " - EMACS"))

  ;; Under `-nw', Emacs emits the title escape only when this is non-nil.
  ;; xterm.el reads it once, during terminal initialisation -- which startup
  ;; runs *after* loading init.el, so setting it from there is early enough
  ;; for the initial terminal frame as well as later `emacsclient -nw' ones.
  ;; It is a defcustom in term/xterm.el, not necessarily loaded yet; setting
  ;; it first is fine, as `defcustom' leaves an already-bound variable alone.
  (setq xterm-set-window-title t))

(provide 'vimacs)
;;; vimacs.el ends here
