;;; vimacs.el --- package install/configure helpers -*- lexical-binding: t; -*-

;;; Commentary:
;; Helper functions used by init.el to declare, install, and configure
;; packages: `configure-packages' records the (PACKAGE . CONFIG-FUNCTION)
;; alist and runs each config function, and `my/install-packages'
;; installs/updates them.

;;; Code:

(require 'package)

(defun my/activate-packages ()
  "Activate installed packages, preferring the fast quickstart path.
`package-quickstart' (set in early-init.el) precompiles every package's
autoloads and load-path into `package-quickstart.el'.  Loading that single
file via `package-activate-all' is ~0.22s faster than `package-initialize',
which scans each package dir.  The file is regenerated by
`my/install-packages'; fall back to the slow scan when it is missing."
  (if (file-exists-p (expand-file-name "package-quickstart.el" user-emacs-directory))
      (package-activate-all)
    (package-initialize)))

;; Activate packages as soon as this file is loaded, so the configuration
;; below (and in init.el) sees them.
(my/activate-packages)

(defun my/load-custom-file ()
  "Point `custom-file' at custom.el and load it if it exists.
Keeps `customize'-written settings out of the hand-maintained init files."
  (setq custom-file (expand-file-name "custom.el" user-emacs-directory))
  (when (file-exists-p custom-file) (load custom-file nil t)))

;; Load customize output as soon as this file is loaded.
(my/load-custom-file)

(defvar my/packages nil
  "Alist of (PACKAGE . CONFIG-FUNCTION), set by `configure-packages'.
`my/install-packages' installs each missing PACKAGE.")

(defun configure-packages (&rest pairs)
  "Declare packages from alternating :NAME CONFIG-FUNCTION arguments.
Each :NAME keyword becomes the symbol NAME.  The resulting
\(PACKAGE . CONFIG-FUNCTION) alist is stored in `my/packages' for
`my/install-packages', and each CONFIG-FUNCTION whose package is
installed is called."
  (setq my/packages
        (let (result)
          (while pairs
            (let ((key (pop pairs))
                  (fn  (pop pairs)))
              (push (cons (intern (substring (symbol-name key) 1)) fn) result)))
          (nreverse result)))
  (dolist (cell my/packages)
    (when (package-installed-p (car cell))
      (funcall (cdr cell)))))

(defun my/install-packages ()
  "Install or update every package in `my/packages'.
Interactively, progress is shown in a dedicated buffer.  In batch mode
it is printed to the terminal instead, so this can be driven from a shell:

    emacs --batch -l ~/.emacs.d/init.el -f my/install-packages

Run interactively via \\[my/install-packages]; it is not called on startup."
  (interactive)
  (let* ((buffer (unless noninteractive (get-buffer-create "*my-package-install*")))
         (out (lambda (fmt &rest args)
                (if noninteractive
                    ;; `message' goes to stderr in batch mode.
                    (message "%s" (apply #'format fmt args))
                  (with-current-buffer buffer
                    (goto-char (point-max))
                    (let ((inhibit-read-only t))
                      (insert (apply #'format fmt args) "\n")))
                  (redisplay t))))
         ;; Mirror package.el's own `message' output into the buffer.  In batch
         ;; mode package.el already logs to stderr, so leave `message' alone
         ;; (advising it here would recurse through `out').
         (relay (lambda (orig fmt &rest args)
                  (when fmt (ignore-errors (apply out fmt args)))
                  (apply orig fmt args))))
    (unless noninteractive
      (with-current-buffer buffer
        (setq buffer-read-only nil)
        (erase-buffer))
      ;; Show the buffer *before* doing the work so progress is visible live.
      (pop-to-buffer buffer)
      (advice-add 'message :around relay))
    (unwind-protect
        (progn
          (funcall out "Refreshing package archives...")
          (package-refresh-contents)
          (dolist (cell my/packages)
            (let ((pkg (car cell)))
              (funcall out "== %s ==" pkg)
              (condition-case err
                  (if (package-installed-p pkg)
                      (package-upgrade pkg)
                    (package-install pkg))
                (error (funcall out "  %s: %s" pkg (error-message-string err))))))
          ;; Rebuild the quickstart file so the next startup uses the fast path.
          (funcall out "Refreshing package-quickstart...")
          (package-quickstart-refresh))
      (unless noninteractive (advice-remove 'message relay)))
    (funcall out "Finished.")))

;;; Font: size chosen from display DPI, set per-frame -------------------------

(defun my/display-dpi (&optional frame)
  "Return the DPI of FRAME's display, or nil if unknown."
  (let* ((attrs (car (display-monitor-attributes-list frame)))
         (mm    (alist-get 'mm-size attrs))
         (geom  (alist-get 'geometry attrs)))
    (when (and mm geom (> (car mm) 0))
      (/ (float (nth 2 geom))            ; width in pixels
         (/ (car mm) 25.4)))))           ; width in inches

(defvar my/font-size-function (lambda (_dpi) 12)
  "Function mapping a display DPI to a font point size.
Set it with `set-conditional-font-size'.")

(defun set-conditional-font-size (fn)
  "Use FN to choose the font point size from a display DPI.
FN is called with one argument, the DPI, and returns a point size."
  (setq my/font-size-function fn))

(defun my/font-size-for-dpi (&optional frame)
  "Pick a font point size based on FRAME's display DPI."
  (funcall my/font-size-function (or (my/display-dpi frame) 96)))

(defun my/set-font-for-frame (&optional frame)
  "Set the frame font once a graphical FRAME exists (needed under daemon)."
  (when (display-graphic-p frame)
    (set-frame-font (font-spec :name "Bitstream Vera Sans Mono"
                               :size (my/font-size-for-dpi frame))
                    nil (list frame))))
(add-hook 'after-make-frame-functions #'my/set-font-for-frame)
(add-hook 'window-setup-hook #'my/set-font-for-frame)

(provide 'vimacs)
;;; vimacs.el ends here
