#!/bin/bash

# this is an simple config to herbstluftwm

pad="17 0 0 0"
function hc() {
    herbstclient "$@"
}

#xsetroot -solid '#D47A55'
hc set window_gap 8
# raindrops
#feh --bg-center ~/Documents/wallpaper/water/rain.jpg
case "$HOSTNAME" in
    ghul)
        feh --bg-scale ~/Documents/wallpaper/nature/02154_standalonecleanwallpaper_2560x1600.jpg
        ;;
    towi04)
        nitrogen --restore
        ;;
    *)
        ;;
esac

# keybindings
Mod=Mod4
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn urxvt
hc keybind $Mod-x spawn ~/scripts/menu/custommenu.sh apps
hc keybind $Mod-F2 spawn gmrun

# tags
hc rename default 1 || true # just try it
for i in {1..9} ; do
    hc add "$i"
    hc keybind "$Mod-$i" use "$i"
    hc keybind "$Mod-Shift-$i" move "$i"
done

# multimonitors
case "$HOSTNAME" in
    towi04)
        # todo: rememberlast tag on monitor 1
        hc remove_monitor 1
        width=1280
        height=1024
        hc move_monitor 0 $((width))x$((height))+0+0 $pad
        hc use 1
        hc add_monitor $((width))x$((height))+$((width))+0 2 $pad
        ;;
    dachs)
        hc remove_monitor 1
        width=1920
        height=1200
        hc move_monitor 0 $((w/2))x$((h))+0+0 $pad
        hc use 1
        hc add_monitor $((w/2))x$((h))+$((w/2))+0 2 $pad
        ;;
    *)
        ;;
esac

# layouting
hc keybind $Mod-i toggle always_show_frame
hc keybind $Mod-r remove
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-Shift-space cycle_layout -1

# focus
hc keybind $Mod-Tab cycle_monitor
hc keybind $Mod-c cycle
hc keybind $Mod-y cycle -1
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

## other things
if [ "$HOSTNAME" = ghul ] ;then
    hc keybind $Mod-q quit
    # TODO: why are there problems with XGrabKey for XF86ScreenSaver;
    hc keybind XF86ScreenSaver spawn ~/bin/lock.sh
    hc keybind XF86Launch1 spawn ~/bin/suspend.sh
fi
if [ "$HOSTNAME" = towi04 ] ; then
    hc keybind $Mod-Control-q spawn ~/scripts/logout-dialog.sh
    hc keybind $Mod-Shift-q spawn ~/scripts/logout-dialog.sh
    hc keybind $Mod-Control-Shift-q quit
    hc keybind Pause spawn ~/scripts/mpd/mpc.sh toggle
    hc keybind Mod4+q spawn ~/scripts/mpd/dmenu.sh play
    hc keybind XF86Stop spawn ~/scripts/mpd/mpc.sh toggle
    hc keybind Mod4+w spawn ~/scripts/mpd/dmenu.sh totem
    hc keybind Mod4+t spawn ~/scripts/utils/iptv/watch-dmenu.sh
    hc keybind Mod1+Mod4+y spawn ~/scripts/mpd/mpc.sh random
    hc keybind Mod1+Mod4+u spawn ~/scripts/mpd/mpc.sh prev
    hc keybind Mod1+Mod4+i spawn ~/scripts/mpd/mpc.sh toggle
    hc keybind Mod1+Mod4+o spawn ~/scripts/mpd/mpc.sh next
    hc keybind Redo spawn ~/scripts/mpd/mpc.sh seek 0
    hc keybind Mod4+F1 spawn ~/scripts/utils/lock.sh
fi

hc keybind Mod4+n spawn ~/scripts/utils/utf8select.sh

hc keybind Shift+XF86AudioMute spawn amixer -q sset PCM toggle
hc keybind XF86AudioMute spawn amixer -q sset Master toggle
hc keybind XF86AudioLowerVolume spawn amixer -q sset Master 2-
hc keybind XF86AudioRaiseVolume spawn amixer -q sset Master 2+

herbstclient set ignore_class 'Xfce4-notifyd|Conky'

# new colors
if [ "$HOSTNAME" = ghul ] ; then
    hc set frame_border_active_color '#49351D'
    hc set frame_border_normal_color '#73532D'
    hc set frame_bg_normal_color '#BD9768'
    hc set frame_bg_active_color '#BD8541'
    hc set frame_border_width 2
    hc set window_border_width 3
    hc set window_border_normal_color '#AE8451'
    hc set window_border_active_color '#F6FF00'
elif [[ "$HOSTNAME" = faui* ]] ; then
    hc set frame_border_active_color '#b20000'
    hc set frame_border_normal_color 'black'
    hc set frame_bg_normal_color '#141414'
    hc set frame_bg_active_color '#580000'
    hc set always_show_frame 1
    hc set frame_border_width 1
    hc set window_gap 0
    hc set frame_bg_transparent 1
    hc set window_border_width 1
    hc set window_border_normal_color '#242424'
    hc set window_border_active_color '#b20000'
else
    hc set frame_border_active_color '#222222'
    hc set frame_border_normal_color '#101010'
    hc set frame_bg_normal_color '#565656'
    hc set frame_bg_active_color '#345F0C'
    hc set frame_border_width 1
    hc set window_border_width 2
    hc set window_border_normal_color '#565656'
    hc set window_border_active_color '#9fbc00'
fi

if [[ "$HOSTNAME" == faui* ]] ;then
    ~/git/herbstluftwm/share/restartpanels.sh
    hc keybind $Mod-x spawn ~/scripts/menu.sh
    hc keybind $Mod-F1 spawn ~/scripts/lock.sh
    hc keybind $Mod-Shift-q quit
    hc keybind $Mod-Control-q quit
    xset -b
else
    ~/dev/c/herbstluftwm/share/restartpanels.sh
fi

