#!/usr/bin/env python3

# config for rofi-bibbrowser
# https://github.com/t-wissmann/rofi-bibbrowser

bib_dirs = [
    BibDir('~/uni/literatur/refs.bib'),
]

# additional directories with PDFs but without bibtex files:
additional_paths = [
    '~/git/papers/Bars-RNNA/literature',
    '~/git/papers/COAX-Literature',
    '~/git/papers/coalgpartref/literature',
]
for p in additional_paths:
    if os.path.exists(os.path.expanduser(p)):
        bib_dirs.append(BibDir(p, bib='/dev/null'))
