#!/bin/bash -e

colornames=(
    black
    red
    green
    yellow
    blue
    magenta
    cyan
    white
    )

printcol() {
    printf "%-12s" "$1"
}

# print header
header=$( printcol Number ; \
        printcol Color ; \
        printcol \ FG ; \
        printcol \ BG ; \
        printcol \ Bold )
echo "$header"
echo "$header" | sed 's/./─/g'
for i in "${!colornames[@]}" ; do
    name=${colornames[$i]}
    printcol "$i"
    printcol "$name"
    echo -n -e "\e[0m\e[3${i}m$(printcol \ $name)\e[0m"
    echo -n -e "\e[0m\e[4${i}m$(printcol \ $name)\e[0m"
    echo -n -e "\e[1m\e[3${i}m$(printcol \ $name)\e[0m"
    echo
    printcol ""
    printcol ""
    echo -n -e "\e[0;3${i}m"
    printcol " \\e[0;3${i}m"
    echo -n -e "\e[0m"
    echo -n -e "\e[0;4${i}m"
    printcol " \\e[0;4${i}m"
    echo -n -e "\e[0m"
    echo -n -e "\e[1;3${i}m"
    printcol " \\e[1;3${i}m"
    echo -n -e "\e[0m"
    echo
done

echo

for i in -1 "${!colornames[@]}" ; do
    for brightness in '' ';1' ; do
        if [[ "$brightness" = "" ]] ; then
            if [[ "$i" -eq -1 ]] ; then
                name='default'
            else
                name="${colornames[$i]}"
            fi
        else
            name=''
        fi
        printf "%-10s" " ${name} "
        # columns = backgrounds
        for j in '' 0 7 black-fg white-fg ; do
            escseq="[0${brightness}"
            case "$j" in
                black-fg)
                    escseq+=";0;$((40+i))"
                    ;;
                white-fg)
                    escseq+=";37;$((40+i))"
                    ;;
                '')
                    escseq+=";$((30+i))"
                    ;;
                *)
                    escseq+=";$((30+i));$((40+j))"
                    ;;
            esac
            escseq+="m"
            echo -ne -e "\e${escseq}"
            printf "%-14s" " ${escseq} "
        done
        echo -e "\e[0m"
    done
done
