#!/bin/bash -e
# announce currently played track in mpd to some irc channel in weechat
# requirements: mpc

notes=( ♩ ♪ ♬ ♫ )
put_notes() {
    echo -n "${notes[$((RANDOM % ${#notes[@]}))]}"
    echo -n "${notes[$((RANDOM % ${#notes[@]}))]}"
}

m() {
    playerctl metadata "$1"
}

msg_prefix=${msg_prefix:-np: $(put_notes) }
msg_suffix=${msg_suffix:- $(put_notes)}
msg="$(m artist) — $(m title) ($(m album))"

msg="${msg_prefix}${msg}${msg_suffix}"
echo "$msg"
echo -n "$msg" | xclip -i
echo -n "$msg" | xclip -i -selection clipboard


