#!/bin/bash -e
# wrapper around xdg-open
file="$1"
filetype=$(xdg-mime query filetype "$file")
default=$(xdg-mime query default "$filetype")

echo -e "Opening \e[32m${file##*/}\e[0m with \e[33m${default%.desktop}\e[0m" >&2
xdg-open "$file" 1>/dev/null 2>/dev/null &
