#!/usr/bin/env bash

cmdname="$0"
print-usage(){
cat <<EOF
Usage: $cmdname FILE

Preview any document supported by pandoc (e.g. markdown) as a man page!
This turns pandoc into a terminal based document viewer.

Written by Thorsten Wissmann (thorsten-wissmann.de) in May 2023.
EOF
}

set -o pipefail

input="$1"
date=$(date '+%Y-%m-%d')

if [[ "$input" = '-h' ]] ; then
    print-usage
    exit 0
fi
if [[ -z "$input" ]] ; then
    print-usage >&2
    exit 1
fi

{
    # First write metadata
    cat <<EOF
.TH "${input}" "PREVIEW" "$date" "\ \& PREVIEW" "\ \&"
EOF
    # then use pandoc to convert.
    pandoc -t man "$input"
    if [[ "$pancode" -ne 0 ]] ; then
        # TODO: kill things later in the pipe
        exit "$?"
    fi
    # Actually, I would like to make all inline 'Code' snippets strong,
    # but replacing t=Code by t=Strong (not affecting t=CodeBlock) via
    #
    #   jq '(.. | select(.t? == "Code")).t = "Strong"' \
    #
    # breaks the json syntax because 'Code' objects are slightly different to 'Strong' ones.
    # So instead, we 'sed' in the roff source and hope that it does not break anything:
} | sed 's,\\f\[V\],\\f[B],g' | man -l -
