#!/usr/bin/env bash

cups_host="russell.informatik.uni-erlangen.de"
host_ip="$(getent hosts "$cups_host" | awk '{ print $1 }' | grep -vx '' | head -n 1 )"
ippurl="ipp://${host_ip}:631/"

commands=(
    cmd-ls
    cmd-lsl
    cmd-help
    cmd-send
)

::() {
    echo -e "\e[1;33m:: \e[0;32m$*\e[0m" >&2
    "$@"
}


cmd-ls() {
    :: ipptool -v -t "$ippurl" /usr/share/cups/ipptool/get-printers.test \
        | grep ' printer-name' | cut -d '=' -f2- | sed 's,^ [ ]*,,'
}

cmd-lsl() {
    :: ipptool -v -t "$ippurl" /usr/share/cups/ipptool/get-printers.test
}

cmd-send() {
    printer="$1"
    filename="$2"
    :: ipptool -v -t \
        -d 'media-size-name=iso_a4_210x297mm' \
        -f "$filename" "${ippurl%%/}/printers/$1" \
        <(cat <<EOF
# Print a test page using print-job
{
	# The name of the test...
	NAME "Print file using Print-Job"

	# The operation to use
	OPERATION Print-Job

	# Attributes, starting in the operation group...
	GROUP operation-attributes-tag
	ATTR charset attributes-charset utf-8
	ATTR language attributes-natural-language en
	ATTR uri printer-uri \$uri
	ATTR name requesting-user-name \$user
	ATTR mimeMediaType document-format \$filetype

	GROUP job-attributes-tag
	ATTR integer copies 1
	# does not seem to work:
	ATTR collection media-col {
		MEMBER keyword media-source tray-1
		MEMBER keyword media-size-name iso_a4_210x297mm
	}

	FILE \$filename

	# What statuses are OK?
	STATUS successful-ok
	STATUS successful-ok-ignored-or-substituted-attributes

	# What attributes do we expect?
	EXPECT job-id
	EXPECT job-uri
}

EOF
)
}

cmd-help() {
    echo "Available commands:"
    for entry in "${commands[@]}" ; do
        echo "${entry#cmd-}"
    done
}


cmd="$1"
shift
for entry in "${commands[@]}" ; do
    if [[ "cmd-$cmd" = "$entry" ]] ; then
        "$entry" "$@"
        exit $?
    fi
done

echo "No such command: \"$cmd\""
cmd-help

