#!/bin/bash

ARGS=( "$@" )

fallback() {
    exec urxvt "${ARGS[@]}"
    exit 1
}

has_cmd() {
    # only filter stdout but keep the error message 'no cmd in...'
    which "$1" 1>/dev/null
}

has_cmd xdotool || fallback
has_cmd pgrep || fallback
has_cmd xprop || fallback
has_cmd readlink || fallback
has_cmd herbstclient || fallback

if ! pid=$(herbstclient \
    and , compare clients.focus.class = URxvt \
        , get_attr clients.focus.pid)
then
    fallback
fi

child_pwd=/proc/$(pgrep -P "$pid"|head -n 1)/cwd
child_pwd=$(readlink -f "$child_pwd") || fallback
echo $child_pwd
exec urxvt -cd "$child_pwd" "${ARGS[@]}"

