#!/usr/bin/env bash

Security=${Security:-wpa} # or wep

# convert to upper case:
Security="${Security^^}"
ESSID="${ESSID:-$1}"
Key="${KEY:-2}"

QRSOURCE="WIFI:S:${ESSID};T:${Security};P:${Key};;"

qrencode -o - --size=10 -t png "${QRSOURCE}" | display
