#!/usr/bin/env bash

Security=${Security:-wpa} # or wep

# convert to upper case:
Security="${Security^^}"
ESSID="${ESSID:-$1}"
Key="${Key:-2}"
output="${output:--}"
QRSOURCE="WIFI:S:${ESSID};T:${Security};P:${Key};;"

echo "$QRSOURCE"

qrencode -o "$output" --size=10 -t png "${QRSOURCE}" | display
