#!/bin/bash

# if a urxvt is focused, then run the given command in the same pwd
# as the child process of the focused urxvt

ARGS=( "$@" )

fallback() {
    exec "${ARGS[@]}"
    exit 1
}

has_cmd() {
    # only filter stdout but keep the error message 'no cmd in...'
    which "$1" 1>/dev/null
}

has_cmd xdotool || fallback
has_cmd pgrep || fallback
has_cmd xprop || fallback
has_cmd readlink || fallback
has_cmd herbstclient || fallback

if ! pid=$(herbstclient get_attr clients.focus.pid)
then
    fallback
fi

child_pwd=/proc/$(pgrep -P "$pid"|head -n 1)/cwd
child_pwd=$(readlink -f "$child_pwd") || fallback
cd "$child_pwd" || true
exec "${ARGS[@]}"

