#!/bin/bash

# if a urxvt is focused, then run the given command in the same pwd
# as the child process of the focused urxvt

add_as_arg=false
if [[ "$1" == '--pwd-as-arg' ]] ; then
    shift
    add_as_arg=true
fi

ARGS=( "$@" )

fallback() {
    exec "${ARGS[@]}"
    exit 1
}

has_cmd() {
    # only filter stdout but keep the error message 'no cmd in...'
    which "$1" 1>/dev/null
}

has_cmd xdotool || fallback
has_cmd pgrep || fallback
has_cmd xprop || fallback
has_cmd readlink || fallback
has_cmd herbstclient || fallback

if ! pid=$(herbstclient get_attr clients.focus.pid 2> /dev/null)
then
    fallback
fi

child_pid=$(pgrep -P "$pid"|head -n 1)
[[ -n "$child_pid" ]] || fallback
child_pwd=/proc/${child_pid}/cwd
child_pwd=$(readlink -f "$child_pwd") || fallback

if [[ "$add_as_arg" = 'true' ]] ; then
    ARGS+=( "$child_pwd" )
else
    cd "$child_pwd" || true
fi
exec "${ARGS[@]}"

