#!/usr/bin/env bash

ZoomLauncher=${ZoomLauncher:-/opt/zoom/ZoomLauncher}

if [[ "$(readlink /usr/bin/zoom)" = "$ZoomLauncher" ]] \
    || [[ "$(readlink $(which zoom))" = "$ZoomLauncher" ]]
then
    echo "Error: /usr/bin/zoom or $(which zoom) is still active!"
    exit 1
fi
mkdir -p $HOME/.zoom-home
exec firejail --quiet --profile=zoom --private=$HOME/.zoom-home -- "$ZoomLauncher" "$@"
