#!/usr/bin/env bash

ZoomLauncher=${ZoomLauncher:-/opt/zoom/ZoomLauncher}

if [[ "$(readlink /usr/bin/zoom)" = "$ZoomLauncher" ]] \
    || [[ "$(readlink $(which zoom))" = "$ZoomLauncher" ]]
then
    echo "Error: /usr/bin/zoom or $(which zoom) is still active!"
    exit 1
fi

# add a bin dir in the home:
mkdir -p $HOME/.zoom-home/bin
export PATH=$PATH:$HOME/bin

if [[ $ZoomLauncher =~ /.* ]] ; then
    ln -svf $ZoomLauncher $HOME/.zoom-home/bin/zoom
fi

exec firejail --quiet --profile=zoom --private=$HOME/.zoom-home -- "$ZoomLauncher" "$@"
