client
dev tun
proto udp
remote 131.188.30.102 943
remote 2001:638:a000:4130:131:188:30:102 943
resolv-retry infinite
user nobody
group nobody
persist-key
persist-tun
nobind

# verify that we are talking to the right server:
verify-x509-name vpn.cip.cs.fau.de name

#redirect-gateway def1
#redirect-gateway ipv6
auth-user-pass


tls-version-min 1.2
auth SHA512

keepalive 10 30
tun-mtu 1280

<ca>
-----BEGIN CERTIFICATE-----
MIIGZzCCBE+gAwIBAgIUMYbLmHvFEKxc/54I3LhZ7SAojiwwDQYJKoZIhvcNAQEL
BQAwgcIxCzAJBgNVBAYTAkRFMQ8wDQYDVQQIDAZCYXllcm4xEDAOBgNVBAcMB0Vy
bGFnZW4xQDA+BgNVBAoMN0ZyaWVkcmljaC1BbGV4YW5kZXItVW5pdmVyc2l0w4PC
pHQgRXJsYW5nZW4tTsODwrxybmJlcmcxDDAKBgNVBAsMA0NJUDEZMBcGA1UEAwwQ
d3d3Y2lwLmNzLmZhdS5kZTElMCMGCSqGSIb3DQEJARYWcHJvYmxlbXNAY2lwLmNz
LmZhdS5kZTAeFw0yMzA5MDgyMzA4MTNaFw0yNzA5MDcyMzA4MTNaMIHCMQswCQYD
VQQGEwJERTEPMA0GA1UECAwGQmF5ZXJuMRAwDgYDVQQHDAdFcmxhZ2VuMUAwPgYD
VQQKDDdGcmllZHJpY2gtQWxleGFuZGVyLVVuaXZlcnNpdMODwqR0IEVybGFuZ2Vu
LU7Dg8K8cm5iZXJnMQwwCgYDVQQLDANDSVAxGTAXBgNVBAMMEHd3d2NpcC5jcy5m
YXUuZGUxJTAjBgkqhkiG9w0BCQEWFnByb2JsZW1zQGNpcC5jcy5mYXUuZGUwggIi
MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC0ldA/e0beIeqhAjFlNX7FuzjX
LDjxAshDA2V9TIKguNv6ye9//r1o8qbG2ITFIUM2T04YvibOzexopttEopS/b0RJ
NtCTx57MGLW4HsAiRqQ6QMaecrdJvSerh7vVuj9d/iHW2unai0mu/YvXookDYrLe
BburP0UeixTOP49iI+Azg6y/zH0gm+p/EWWLLsUL+7KP35sXa6FRvBcwmojpsfto
WQ4vnP6neOY8Tj+swg4pV3Y0+ahBwtb5mJ91/c/GKx0pa0PGzVrTlA/Pxrfg/xcV
8c5OFFsbEK/U4Y5q0xVn/Ub33vFFivGc1fjEysSxSah6lnAa3bOWXHUu+2HpyIq9
9FVp5IUlIC52PT6m95X5ozFIm0BEuOZziVkv3IFNUCuRdl6eEWPh+tY2vBbxSR6T
N0TGxq7bo2Ap7mK9teVRb3lHlEMjmCIkfcdLythNuD1QDae1JzmsG28yXzbS8THd
ndU+nJsAyK91jsU+2U/VX2B/Ho2WL8J0VexI59vBa2dSIDAdkivHaY2cMqlk087X
TU5TcqtWOy9YLsd9HPKsh3cYtIqF2opPP8vxLPPhq0uOFgbktys6wnrEIIJhGJnU
cO/56xYFzR80nAe1o+Bec9c+sePjm6Dt2anD0dVHQj+FqkdY/wQyaA5ezfMtd4/Q
zFcjbZaUTD5yECnZBQIDAQABo1MwUTAdBgNVHQ4EFgQUAWKM+rXeDQAIdRQLwTbx
zD1i114wHwYDVR0jBBgwFoAUAWKM+rXeDQAIdRQLwTbxzD1i114wDwYDVR0TAQH/
BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEAhMppInvIhwcj/Ih5f0AzR/SIr7sk
psI/dyW0Zqrw7sAQLK333FvM1QjIV7bH7KLxviTC/NUN1vzO2XUiIIqhWW/sPjEZ
BaC5ni8JwImppaNnQELv0HD9hniIpJijJb013f9AQUxPFqYhiqMYYdS7qF1NMMm6
cLHsjGhI7acgjndZai6sIJXN3oTWxj6k1b7hMjA2C+UsWZ2L0ahaE1tJmtAqnxsA
eUhOb/lSuTbLLlbmUJ3pjLRw7V/A7ZQ7Ste5/REHPqObxbtTu4muzSB0Q7h6Ysvf
pMr6O5lNHOwZo13aCZYP916N8JEzZdgmDSRp7fDWwRBYMQYhNowWnrOZyInDCN8b
oQKnp+Qmw64VRB3WaePhzgiQ3yApQ2y4L9vjuKD1Bzg92dkrw0HOpFNzL8bWLOu8
OwgbPlu7D4tNH3ueoGvuvOK7ZP1WbsPe4iHtqS90IwqyJlWVSQXJAfuoVLVhapY5
X7nQD+CHidNRSL8gmRGpUfxPZDBEpxbPKFKg7EdmaEa8CVU5fAlbMABYlHpOZIob
3j+ocG5EmclNhKxFR2723lRR9+HX5WNP/OCbWutO6fIU2EZLTv7xEJQWMWH99suN
/D/7zcl3K+jRpJcAkKlOKcqb1S2hDam0wBCna9az8IAEi9UajMG9K9HiYH0RPtL4
VO8ERFExhP13lGE=
-----END CERTIFICATE-----
</ca>
