#!/bin/bash -e

IFS=$'\n'
stop_all='[ STOP ALL PROFILES ]'
mapfile -d '' -t profiles \
    < <(find /etc/netctl/ \
            -maxdepth 1 -type f  -printf '%f\n' \
            | grep -xvE '\..*|.*~' \
            | sort )
# I'm unsure whether I really should filter out all hidden files

profiles=(
    "$stop_all"
    "${profiles[@]}"
)

i=0
active_name=$(systemctl list-units --state=active --no-pager --no-legend  'netctl*.service')
active_name=${active_name%%.service*}
active=""
for p in "${profiles[@]}" ; do
    if [ "${p}" == "$active_name" ] ; then
        active="$i"
    fi
    i=$((i+1))
done

message=$(sudo journalctl -n 10 -o short --unit=system-netctl.slice)

selection=$(printf "%s\n" "${profiles[@]}" \
    | rofi \
      -dmenu \
      -i \
      -a "0,$active" \
      -no-custom \
      -p "netctl enable" \
      -mesg "<i></i>$message"
      )

if [ "$selection" = "$stop_all" ] ; then
    sudo netctl stop-all
else
    connect() {
        ::() { echo -e "\e[1;32m::\e[1;37m $*\e[0m" ; }
        :: sudo journalctl -f  --unit='system-netctl.slice' '&'
        sudo journalctl -f  --unit='system-netctl.slice' &
        journalctl_pid=$!
        :: sudo netctl stop-all
        sudo netctl stop-all
        :: sudo netctl start "$selection"
        sudo netctl start "$selection"
        sudo netctl wait-online "$selection"
        :: Press any key to close… | tr -d '\n'
        read -n 1
        kill "$journalctl_pid"
    }
    export selection
    export -f connect
    urxvt -title "netctl start $selection" -e bash -c connect
fi


